import assert from 'node:assert/strict';
import { createMemory, InMemoryStorage } from 'topic-memory';
import { createScriptedLlm, questions, seedConversation } from './scenario.mjs';
const memory = createMemory({ storage: new InMemoryStorage(), llm: createScriptedLlm() });
await seedConversation(memory);
assert.equal((await memory.maybeRunTopicWorker()).reason, 'accepted');
const result = await memory.retrieve({ userMessage: questions[0].question });
assert.deepEqual(result.selectedTopicIds, ['T1']);
assert.ok(result.memoryContext.includes('14000 yen'));
assert.ok(!result.recentContext.some(e => e.userText.includes('14000 yen')));
console.log('SCRIPTED DEMO — real SDK, fixed model responses; not an AI benchmark.');
console.log('Question:', questions[0].question);
console.log('Last 5 exchanges contain the hotel budget: no');
console.log('Selected topics:', result.selectedTopicIds.join(', '));
console.log('Restored original conversation:\n' + result.memoryContext);
